#!/usr/bin/env tclsh9.0
#
# Usage: img_pkgindex.tcl <out> <imgVer> <zlibVer> <pngVer> <jpegVer> <tiffVer>
#
# Emits a pkgIndex.tcl for the statically-linked Img/tkimg packages. Each entry
# uses `load {} <Prefix>` so it resolves to the matching Tcl_StaticPackage
# registration in kitsh.c (see #ifdef WITH_IMG block). Img's own pkgIndex files
# can't be used directly: they reference .a paths that Tcl's `load` can't open,
# and Img's `make install` skips the umbrella concat for static builds anyway.

lassign $argv outFile imgVer zlibVer pngVer jpegVer tiffVer

# pkg-name -> Tcl_StaticPackage prefix (case-sensitive; must match kitsh.c)
set basePkgs [list \
    img::base   Tkimg    $imgVer  \
    zlibtcl     Zlibtcl  $zlibVer \
    pngtcl      Pngtcl   $pngVer  \
    jpegtcl     Jpegtcl  $jpegVer \
    tifftcl     Tifftcl  $tiffVer]

set formatPkgs [list \
    img::bmp    Tkimgbmp    \
    img::dted   Tkimgdted   \
    img::flir   Tkimgflir   \
    img::gif    Tkimggif    \
    img::ico    Tkimgico    \
    img::jpeg   Tkimgjpeg   \
    img::pcx    Tkimgpcx    \
    img::pixmap Tkimgpixmap \
    img::png    Tkimgpng    \
    img::ppm    Tkimgppm    \
    img::ps     Tkimgps     \
    img::raw    Tkimgraw    \
    img::sgi    Tkimgsgi    \
    img::sun    Tkimgsun    \
    img::tga    Tkimgtga    \
    img::tiff   Tkimgtiff   \
    img::window Tkimgwindow \
    img::xbm    Tkimgxbm    \
    img::xpm    Tkimgxpm]

set fd [open $outFile w]
puts $fd "# Generated by zippy/img_pkgindex.tcl — do not edit."
puts $fd "# Resolves Img/tkimg sub-packages to statically-linked Tcl_StaticPackage entries."

foreach {pkg prefix ver} $basePkgs {
    puts $fd [list package ifneeded $pkg $ver [list load {} $prefix]]
}
foreach {pkg prefix} $formatPkgs {
    puts $fd [list package ifneeded $pkg $imgVer [list load {} $prefix]]
}

# Umbrella `Img` package: loads the common subset (matches upstream — excludes
# dted, flir, gif, raw, ps which have no auto-detect magic or need external
# programs like Ghostscript). Order is reversed so format auto-detection tries
# magic-laden formats last.
puts $fd ""
puts $fd "package ifneeded Img $imgVer \{"
foreach f {window tga ico pcx sgi sun xbm xpm jpeg png tiff bmp ppm pixmap} {
    puts $fd "    package require img::$f"
}
puts $fd "    package provide Img $imgVer"
puts $fd "\}"

close $fd
puts "Wrote $outFile"
