#!/usr/bin/env tclsh9.0
#
# Usage: img_pkgindex.tcl <out> <imgVer> <zlibVer> <pngVer> <jpegVer> <tiffVer>
#                        <basePkgs> <formats>
#
# basePkgs and formats are space-separated lists (a subset of all known
# packages — `IMG_INCLUDE` in zippy.mk drives the whitelist). Emits a
# pkgIndex.tcl that resolves only those packages via `load {} <Prefix>`,
# matching the Tcl_StaticPackage entries that kitsh.c compiles in for the
# same set. Img's own pkgIndex files can't be used directly: they reference
# .a paths that Tcl's `load` can't open, and Img's `make install` skips the
# umbrella concat for static builds anyway.

lassign $argv outFile imgVer zlibVer pngVer jpegVer tiffVer basePkgsStr formatsStr

set basePkgs [regexp -all -inline {\S+} $basePkgsStr]
set formats  [regexp -all -inline {\S+} $formatsStr]

# base name -> {package-name Tcl_StaticPackage-prefix version}
array set baseInfo [list \
    tkimg   [list img::base Tkimg    $imgVer]  \
    zlibtcl [list zlibtcl   Zlibtcl  $zlibVer] \
    pngtcl  [list pngtcl    Pngtcl   $pngVer]  \
    jpegtcl [list jpegtcl   Jpegtcl  $jpegVer] \
    tifftcl [list tifftcl   Tifftcl  $tiffVer]]

# format name -> Tcl_StaticPackage prefix (case-sensitive; must match kitsh.c)
array set formatPrefix {
    bmp    Tkimgbmp
    dted   Tkimgdted
    flir   Tkimgflir
    gif    Tkimggif
    ico    Tkimgico
    jpeg   Tkimgjpeg
    pcx    Tkimgpcx
    pixmap Tkimgpixmap
    png    Tkimgpng
    ppm    Tkimgppm
    ps     Tkimgps
    raw    Tkimgraw
    sgi    Tkimgsgi
    sun    Tkimgsun
    tga    Tkimgtga
    tiff   Tkimgtiff
    window Tkimgwindow
    xbm    Tkimgxbm
    xpm    Tkimgxpm
}

set fd [open $outFile w]
puts $fd "# Generated by zippy/img_pkgindex.tcl — do not edit."
puts $fd "# Resolves Img/tkimg sub-packages to statically-linked Tcl_StaticPackage entries."

foreach b $basePkgs {
    lassign $baseInfo($b) pkg prefix ver
    puts $fd [list package ifneeded $pkg $ver [list load {} $prefix]]
}
foreach f $formats {
    puts $fd [list package ifneeded img::$f $imgVer [list load {} $formatPrefix($f)]]
}

# Umbrella `Img` package: requires the standard auto-detect subset
# intersected with the whitelist, so dropping (say) png from IMG_INCLUDE
# just drops it from the umbrella `package require Img` too. The default
# subset matches upstream Img — dted/flir/gif/raw/ps are excluded since
# they have no auto-detect magic or need external programs like
# Ghostscript. Order is reversed so format auto-detection tries
# magic-laden formats last.
set umbrella {}
foreach f {window tga ico pcx sgi sun xbm xpm jpeg png tiff bmp ppm pixmap} {
    if {[lsearch -exact $formats $f] >= 0} {
        lappend umbrella $f
    }
}

puts $fd ""
puts $fd "package ifneeded Img $imgVer \{"
foreach f $umbrella {
    puts $fd "    package require img::$f"
}
puts $fd "    package provide Img $imgVer"
puts $fd "\}"

close $fd
puts "Wrote $outFile"
