# blob2c.tcl - a file as a C byte array.
#
#   tclsh blob2c.tcl <in> <out.c> <symbol>
#
# Emits <symbol>_start[] and <symbol>_len. This stands in for `ld -r -b binary`
# on a target whose linker has no such mode and whose assembler rejects
# .incbin (wasm32). The one difference from ld's symbols: there is no
# <symbol>_end. A C array cannot give a second symbol that sits exactly at its
# end, so consumers of the wasm build take the length instead - the shims
# accept (start, len) and the native ones compute len as end - start.
#
# Compile time is the cost: clang takes ~1.5 s per MB of initialiser, which is
# fine for something that only reruns when the bundled scripts change.

if {[llength $argv] != 3} {
    puts stderr "usage: blob2c.tcl in out.c symbol"
    exit 2
}
lassign $argv in out sym

set f [open $in rb]
set data [read $f]
close $f
set n [string length $data]

binary scan $data cu* bytes

set o [open $out w]
puts $o "/* generated by zippy/emscripten/blob2c.tcl from [file tail $in] - do not edit */"
puts $o "const unsigned long ${sym}_len = ${n}UL;"
puts $o "__attribute__((aligned(16))) const unsigned char ${sym}_start\[[expr {$n > 0 ? $n : 1}]\] = {"
set per 32
for {set i 0} {$i < $n} {incr i $per} {
    puts $o "[join [lrange $bytes $i [expr {$i + $per - 1}]] ,],"
}
puts $o "};"
close $o
